apiVersion: apps/v1
kind: Deployment
metadata:
  name: ser-demp-depl
spec:

  template:
    metadata:
      name: ng-deploy
      labels:
        type: webserver
    spec:
      containers:
        - name: nginx-img
          image: nginx

  replicas: 3
  selector:
    matchLabels:
       type: webserver

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
        type: webserver
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
